# Generated by Django 3.2.2 on 2021-05-06 22:15

from django.db import migrations, models
import dividends.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dividends',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('dividend_amount', models.DecimalField(max_digits=10, decimal_places=2)),
            ],
        ),
    ]
