# Generated by Django 4.2.5 on 2023-09-08 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dividends',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('dividend_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
